# Generated by Django 2.1.5 on 2019-01-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocuklaricin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocuklaricin_api.Fund'),
        ),
    ]
