# Generated by Django 2.1.5 on 2019-01-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocuklaricin_api', '0003_auto_20190117_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocuklaricin_api.Fund'),
        ),
    ]
