# Generated by Django 2.1.5 on 2019-01-20 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocuklaricin_api', '0005_auto_20190119_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='fund',
        ),
        migrations.AddField(
            model_name='fund',
            name='machine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cocuklaricin_api.Machine'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 9, 33, 47, 853591)),
        ),
    ]
