# Generated by Django 2.1.5 on 2019-01-20 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cocuklaricin_api', '0007_auto_20190120_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 20, 9, 39, 23, 300116, tzinfo=utc)),
        ),
    ]
